### ISSUE TITLE
Problem to build SKR1.4 Turbo

### ISSUE THREAD

**Issue by Buggins77** [bigtreetech/BIGTREETECH-SKR-V1.3#195]
**During compilation via "Sublime Text" (using Deviot for compiling and 1769 acc) i have got:**
*** [.pio\build\LPC1769\src\src\HAL\HAL_LPC1768\DebugMonitor.cpp.o] Error 1
*** [.pio\build\LPC1769\src\src\HAL\HAL_LPC1768\HAL.cpp.o] Error 1
*** [.pio\build\LPC1769\src\src\HAL\HAL_LPC1768\HAL_SPI.cpp.o] Error 1

**Tryng to use VSC, and Marlin Build i have follow issue:**
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\fw\Marlin-bugfix-2.0.x>python buildroot/share/atom/auto_build.py build
pwd:  C:/fw/Marlin-bugfix-2.0.x
build_type:   build

Working

python version 2.7.17
build_type:   build
starting platformio
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "buildroot/share/atom/auto_build.py", line 1099, in <lambda>
    self.secondary_thread = threading.Thread(target=lambda q, arg1: q.put(run_PIO(arg1)), args=(que, ''))
  File "buildroot/share/atom/auto_build.py", line 907, in run_PIO
    ['platformio', 'run', '-e', target_env], stdout=subprocess.PIPE, stderr=subprocess.STDOUT
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2]

and no any result ((((

**Comment by Buggins77** [comment]
> **During compilation via "Sublime Text" (using Deviot for compiling and 1769 acc) i have got:**
> *** [.pio\build\LPC1769\src\src\HAL\HAL_LPC1768\DebugMonitor.cpp.o] Error 1
> *** [.pio\build\LPC1769\src\src\HAL\HAL_LPC1768\HAL.cpp.o] Error 1
> *** [.pio\build\LPC1769\src\src\HAL\HAL_LPC1768\HAL_SPI.cpp.o] Error 1
> 
> **Tryng to use VSC, and Marlin Build i have follow issue:**
> Microsoft Windows [Version 6.1.7601]
> Copyright (c) 2009 Microsoft Corporation. All rights reserved.
> 
> C:\fw\Marlin-bugfix-2.0.x>python buildroot/share/atom/auto_build.py build
> pwd: C:/fw/Marlin-bugfix-2.0.x
> build_type: build
> 
> Working
> 
> python version 2.7.17
> build_type: build
> starting platformio
> Exception in thread Thread-1:
> Traceback (most recent call last):
> File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
> self.run()
> File "C:\Python27\lib\threading.py", line 754, in run
> self.__target(*self.__args, **self.__kwargs)
> File "buildroot/share/atom/auto_build.py", line 1099, in
> self.secondary_thread = threading.Thread(target=lambda q, arg1: q.put(run_PIO(arg1)), args=(que, ''))
> File "buildroot/share/atom/auto_build.py", line 907, in run_PIO
> ['platformio', 'run', '-e', target_env], stdout=subprocess.PIPE, stderr=subprocess.STDOUT
> File "C:\Python27\lib\subprocess.py", line 394, in **init**
> errread, errwrite)
> File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
> startupinfo)
> WindowsError: [Error 2]
> 
> and no any result ((((

**Comment by Buggins77** [comment]
Problem solved. Was wrong version of Python
